version: '3.0'

services:
  db:
    container_name: ratemeDb
    build:
      context: ./dockerDB
      dockerfile: Dockerfile
    volumes:
    - ./dockerDB/DbVolume:/var/lib/mysql
    - ./dockerDB/DbConfig:/etc/mysql/conf.d
    environment:
    - MYSQL_DATABASE=osm01
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
  app:
    container_name: ratemeApp
    build:
      context: ./
      dockerfile: dockerApp/Dockerfile
    environment:
      DB_NAME: osm01
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PW: ''
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
      KAFKA_TOPIC: rating
    depends_on:
      - db
      - kafka
    ports:
    - 9080:9080
    - 9443:9443
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    container_name: zookeeper
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafkareader:
    container_name: kafkaReader
    build:
      context: ./
      dockerfile: dockerKafkaReader/Dockerfile
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
      KAFKA_TOPIC: rating
    depends_on:
      - kafka