version: '3.0'

services:
  db:
    container_name: rateMeDbContainer
    build:
      context: ./dockerDB
      dockerfile: Dockerfile
    volumes:
    - ./dockerDB/DbVolume:/var/lib/mysql
    - ./dockerDB/DbConfig:/etc/mysql/conf.d
    environment:
    - MYSQL_DATABASE=osm01
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
    - 3306:3306